export interface Slide {
  key: string;
  name: string;
  category: string;
}

export const ALL_SLIDES: Slide[] = [
  { key: "skeletal_muscle", name: "Skeletal Muscle", category: "Muscle" },
  { key: "cardiac_muscle", name: "Cardiac Muscle", category: "Muscle" },
  { key: "elastic_artery", name: "Elastic Artery", category: "Vascular" },
  { key: "muscular_artery", name: "Muscular Artery", category: "Vascular" },
  { key: "large_vein", name: "Large Vein", category: "Vascular" },
  { key: "elastic_cartilage", name: "Elastic Cartilage", category: "Connective Tissue" },
  { key: "elastic_cartilage_2", name: "Elastic Cartilage (II)", category: "Connective Tissue" },
  { key: "hyaline_cartilage", name: "Hyaline Cartilage", category: "Connective Tissue" },
  { key: "fibrocartilage", name: "Fibrocartilage", category: "Connective Tissue" },
  { key: "bone_transverse", name: "Bone – Transverse Section", category: "Connective Tissue" },
  { key: "bone_longitudinal", name: "Bone – Longitudinal Section", category: "Connective Tissue" },
  { key: "sensory_ganglia", name: "Sensory Ganglia", category: "Nervous" },
  { key: "sensory_ganglia_2", name: "Sensory Ganglia (II)", category: "Nervous" },
  { key: "autonomic_ganglia", name: "Autonomic Ganglia", category: "Nervous" },
  { key: "autonomic_ganglia_2", name: "Autonomic Ganglia (II)", category: "Nervous" },
  { key: "thin_skin", name: "Thin Skin", category: "Integumentary" },
  { key: "thick_skin", name: "Thick Skin", category: "Integumentary" },
  { key: "lymph_node", name: "Lymph Node", category: "Lymphoid" },
  { key: "lymph_node_2", name: "Lymph Node (II)", category: "Lymphoid" },
  { key: "thymus", name: "Thymus", category: "Lymphoid" },
  { key: "thymus_2", name: "Thymus (II)", category: "Lymphoid" },
  { key: "tonsil", name: "Tonsil", category: "Lymphoid" },
  { key: "tonsil_2", name: "Tonsil (II)", category: "Lymphoid" },
  { key: "spleen", name: "Spleen", category: "Lymphoid" },
  { key: "placenta", name: "Placenta", category: "Reproductive" },
  { key: "umbilical_cord", name: "Umbilical Cord", category: "Reproductive" },
  { key: "mixed_salivary_gland", name: "Mixed Salivary Gland", category: "GIT" },
  { key: "mixed_salivary_gland_2", name: "Mixed Salivary Gland (II)", category: "GIT" },
  { key: "mucous_salivary_gland", name: "Mucous Salivary Gland", category: "GIT" },
  { key: "serous_salivary_gland", name: "Serous Salivary Gland", category: "GIT" },
  { key: "liver", name: "Liver", category: "GIT" },
  { key: "gall_bladder", name: "Gall Bladder", category: "GIT" },
  { key: "tongue", name: "Tongue", category: "GIT" },
  { key: "tongue_2", name: "Tongue (II)", category: "GIT" },
  { key: "esophagus", name: "Esophagus", category: "GIT" },
  { key: "esophagus_2", name: "Esophagus (II)", category: "GIT" },
  { key: "stomach_fundus", name: "Stomach – Fundus", category: "GIT" },
  { key: "stomach_fundus_2", name: "Stomach – Fundus (II)", category: "GIT" },
  { key: "stomach_pylorus", name: "Stomach – Pylorus", category: "GIT" },
  { key: "duodenum", name: "Duodenum", category: "GIT" },
  { key: "duodenum_2", name: "Duodenum (II)", category: "GIT" },
  { key: "jejunum", name: "Jejunum", category: "GIT" },
  { key: "ileum", name: "Ileum", category: "GIT" },
  { key: "appendix", name: "Appendix", category: "GIT" },
  { key: "appendix_2", name: "Appendix (II)", category: "GIT" },
  { key: "large_intestine", name: "Large Intestine", category: "GIT" },
  { key: "testis", name: "Testis", category: "Reproductive" },
  { key: "testis_2", name: "Testis (II)", category: "Reproductive" },
  { key: "epididymis", name: "Epididymis", category: "Reproductive" },
  { key: "vas_deferens", name: "Vas Deferens", category: "Reproductive" },
  { key: "kidney", name: "Kidney", category: "Urinary" },
  { key: "fallopian_tube", name: "Fallopian Tube", category: "Reproductive" },
  { key: "ovary", name: "Ovary", category: "Reproductive" },
  { key: "uterus_proliferative", name: "Uterus – Proliferative Phase", category: "Reproductive" },
  { key: "lung", name: "Lung", category: "Respiratory" },
  { key: "trachea", name: "Trachea", category: "Respiratory" },
  { key: "suprarenal_gland", name: "Suprarenal Gland", category: "Endocrine" },
  { key: "mammary_gland", name: "Mammary Gland (Inactive)", category: "Integumentary" },
  { key: "pituitary_gland", name: "Pituitary Gland", category: "Endocrine" },
  { key: "cornea", name: "Cornea", category: "Special Senses" },
  { key: "retina", name: "Retina", category: "Special Senses" },
  { key: "cerebrum", name: "Cerebrum", category: "Nervous" },
];

export const SLIDE_CATEGORIES = [
  "All",
  "Muscle",
  "Vascular",
  "Connective Tissue",
  "Nervous",
  "Integumentary",
  "Lymphoid",
  "GIT",
  "Reproductive",
  "Urinary",
  "Respiratory",
  "Endocrine",
  "Special Senses",
];

export const slideImageMap: Record<string, any> = {
  skeletal_muscle: require("../assets/images/slides/skeletal_muscle.jpg"),
  cardiac_muscle: require("../assets/images/slides/cardiac_muscle.jpg"),
  elastic_artery: require("../assets/images/slides/elastic_artery.jpg"),
  muscular_artery: require("../assets/images/slides/muscular_artery.jpg"),
  large_vein: require("../assets/images/slides/large_vein.jpg"),
  elastic_cartilage: require("../assets/images/slides/elastic_cartilage.jpg"),
  elastic_cartilage_2: require("../assets/images/slides/elastic_cartilage_2.jpg"),
  hyaline_cartilage: require("../assets/images/slides/hyaline_cartilage.jpg"),
  fibrocartilage: require("../assets/images/slides/fibrocartilage.jpg"),
  bone_transverse: require("../assets/images/slides/bone_transverse.jpg"),
  bone_longitudinal: require("../assets/images/slides/bone_longitudinal.jpg"),
  sensory_ganglia: require("../assets/images/slides/sensory_ganglia.jpg"),
  sensory_ganglia_2: require("../assets/images/slides/sensory_ganglia_2.jpg"),
  autonomic_ganglia: require("../assets/images/slides/autonomic_ganglia.jpg"),
  autonomic_ganglia_2: require("../assets/images/slides/autonomic_ganglia_2.jpg"),
  thin_skin: require("../assets/images/slides/thin_skin.jpg"),
  thick_skin: require("../assets/images/slides/thick_skin.jpg"),
  lymph_node: require("../assets/images/slides/lymph_node.jpg"),
  lymph_node_2: require("../assets/images/slides/lymph_node_2.jpg"),
  thymus: require("../assets/images/slides/thymus.jpg"),
  thymus_2: require("../assets/images/slides/thymus_2.jpg"),
  tonsil: require("../assets/images/slides/tonsil.jpg"),
  tonsil_2: require("../assets/images/slides/tonsil_2.jpg"),
  spleen: require("../assets/images/slides/spleen.jpg"),
  placenta: require("../assets/images/slides/placenta.jpg"),
  umbilical_cord: require("../assets/images/slides/umbilical_cord.jpg"),
  mixed_salivary_gland: require("../assets/images/slides/mixed_salivary_gland.jpg"),
  mixed_salivary_gland_2: require("../assets/images/slides/mixed_salivary_gland_2.jpg"),
  mucous_salivary_gland: require("../assets/images/slides/mucous_salivary_gland.jpg"),
  serous_salivary_gland: require("../assets/images/slides/serous_salivary_gland.jpg"),
  liver: require("../assets/images/slides/liver.jpg"),
  gall_bladder: require("../assets/images/slides/gall_bladder.jpg"),
  tongue: require("../assets/images/slides/tongue.jpg"),
  tongue_2: require("../assets/images/slides/tongue_2.jpg"),
  esophagus: require("../assets/images/slides/esophagus.jpg"),
  esophagus_2: require("../assets/images/slides/esophagus_2.jpg"),
  stomach_fundus: require("../assets/images/slides/stomach_fundus.jpg"),
  stomach_fundus_2: require("../assets/images/slides/stomach_fundus_2.jpg"),
  stomach_pylorus: require("../assets/images/slides/stomach_pylorus.jpg"),
  duodenum: require("../assets/images/slides/duodenum.jpg"),
  duodenum_2: require("../assets/images/slides/duodenum_2.jpg"),
  jejunum: require("../assets/images/slides/jejunum.jpg"),
  ileum: require("../assets/images/slides/ileum.jpg"),
  appendix: require("../assets/images/slides/appendix.jpg"),
  appendix_2: require("../assets/images/slides/appendix_2.jpg"),
  large_intestine: require("../assets/images/slides/large_intestine.jpg"),
  testis: require("../assets/images/slides/testis.jpg"),
  testis_2: require("../assets/images/slides/testis_2.jpg"),
  epididymis: require("../assets/images/slides/epididymis.jpg"),
  vas_deferens: require("../assets/images/slides/vas_deferens.jpg"),
  kidney: require("../assets/images/slides/kidney.jpg"),
  fallopian_tube: require("../assets/images/slides/fallopian_tube.jpg"),
  ovary: require("../assets/images/slides/ovary.jpg"),
  uterus_proliferative: require("../assets/images/slides/uterus_proliferative.jpg"),
  lung: require("../assets/images/slides/lung.jpg"),
  trachea: require("../assets/images/slides/trachea.jpg"),
  suprarenal_gland: require("../assets/images/slides/suprarenal_gland.jpg"),
  mammary_gland: require("../assets/images/slides/mammary_gland.jpg"),
  pituitary_gland: require("../assets/images/slides/pituitary_gland.jpg"),
  cornea: require("../assets/images/slides/cornea.jpg"),
  retina: require("../assets/images/slides/retina.jpg"),
  cerebrum: require("../assets/images/slides/cerebrum.jpg"),
};
