uploads = []

[[generated]]
id = "JoacGhzjmjtPCymUXhmR_"
uri = "file://artifacts/mobile/assets/images/icon.png"
type = "image"
title = "histospotter app icon"

[[generated]]
id = "0vzijO0hLElEsbLib0S8U"
uri = "file://artifacts/mobile/assets/images/histo_epithelial.png"
type = "image"
title = "epithelial histology slide"

[[generated]]
id = "NUXmOm7TUYgWafA7Bn_xj"
uri = "file://artifacts/mobile/assets/images/histo_muscle.png"
type = "image"
title = "muscle histology slide"

[[generated]]
id = "_CNh5148E5fFTUPVhtzo6"
uri = "file://artifacts/mobile/assets/images/histo_kidney.png"
type = "image"
title = "kidney histology slide"

[[generated]]
id = "Y39nS1TTevHiWM6awC3pO"
uri = "file://artifacts/mobile/assets/images/histo_nerve.png"
type = "image"
title = "nerve histology slide"

[[generated]]
id = "c3uX8B5iPexmyxIYLenn4"
uri = "file://artifacts/mobile/assets/images/histo_liver.png"
type = "image"
title = "liver histology slide"

[[generated]]
id = "mb3aJmgv75jktT5C2EEPl"
uri = "file://artifacts/mobile/assets/images/histo_lung.png"
type = "image"
title = "lung histology slide"

[[generated]]
id = "e4xqxLs_hNYLqhwoNhJLM"
uri = "file://artifacts/mobile/assets/images/histo_skin.png"
type = "image"
title = "skin histology slide"

[[generated]]
id = "-amUj53asbnZyDk-ESsdx"
uri = "file://artifacts/mobile/assets/images/thumbnails/histology.png"
type = "image"
title = "histology slide thumbnail"

[[generated]]
id = "_xolnFtOfBgb-Z_FE5Klg"
uri = "file://artifacts/mobile/assets/images/thumbnails/head_neck.png"
type = "image"
title = "head neck anatomy thumbnail"

[[generated]]
id = "N8w1DdXt-rgDY-xKJN2VO"
uri = "file://artifacts/mobile/assets/images/thumbnails/upper_limb.png"
type = "image"
title = "upper limb anatomy thumbnail"

[[generated]]
id = "29Q6gr97zorB4PgFUO5JS"
uri = "file://artifacts/mobile/assets/images/thumbnails/thorax.png"
type = "image"
title = "thorax heart anatomy thumbnail"

[[generated]]
id = "ROGycwUfJmv_fITNJ4rWc"
uri = "file://artifacts/mobile/assets/images/thumbnails/abdomen.png"
type = "image"
title = "abdomen anatomy thumbnail"

[[generated]]
id = "Plpk2XUEmVV51Vg89hh8-"
uri = "file://artifacts/mobile/assets/images/thumbnails/neuroanatomy.png"
type = "image"
title = "brain neuroanatomy thumbnail"

[[generated]]
id = "RbpO3-oHj-NS9V5yen-md"
uri = "file://artifacts/mobile/assets/images/thumbnails/embryology.png"
type = "image"
title = "embryology stages thumbnail"

[[generated]]
id = "Jx-izxnayYWam4kohUVJT"
uri = "file://artifacts/mobile/assets/images/thumbnails/osteology.png"
type = "image"
title = "osteology bones thumbnail"

[[generated]]
id = "V_V0m6xSAPceY64AcLuhj"
uri = "file://artifacts/mobile/assets/images/ospe/p001_venipuncture.png"
type = "image"
title = "generated_image"

[[generated]]
id = "jLqRolPLuUGT2jQKP4vC9"
uri = "file://artifacts/mobile/assets/images/ospe/p002_hernia.png"
type = "image"
title = "generated_image"

[[generated]]
id = "25ZQUnP0783-GEvrNscyT"
uri = "file://artifacts/mobile/assets/images/ospe/p003_ape_hand.png"
type = "image"
title = "generated_image"

[[generated]]
id = "Oe3dGqiqmvc6jBG7JZroB"
uri = "file://artifacts/mobile/assets/images/ospe/p004_trendelenburg.png"
type = "image"
title = "generated_image"

[[generated]]
id = "-_wrNw5CDop8Vs-ZCaBPv"
uri = "file://artifacts/mobile/assets/images/ospe/p005_varicose.png"
type = "image"
title = "generated_image"

[[generated]]
id = "PNfWIPYEhk5SETG1eOt_r"
uri = "file://artifacts/mobile/assets/images/ospe/p006_lumbar_puncture.png"
type = "image"
title = "generated_image"

[[generated]]
id = "kFEj1qe_3dNaYV_JrCTd_"
uri = "file://artifacts/mobile/assets/images/ospe/p007_raccoon_eyes.png"
type = "image"
title = "generated_image"

[[generated]]
id = "TP6fgbrP0sG_dk6Iz79y2"
uri = "file://artifacts/mobile/assets/images/ospe/p008_birth_injuries.png"
type = "image"
title = "generated_image"

[[generated]]
id = "JD3htb3nB7bCbodvqHBPp"
uri = "file://artifacts/mobile/assets/images/ospe/p009_claw_hand.png"
type = "image"
title = "generated_image"

[[generated]]
id = "MsO9kksKYOTUUJ4AUoIBY"
uri = "file://artifacts/mobile/assets/images/ospe/p010_caput_medusae.png"
type = "image"
title = "generated_image"

[[generated]]
id = "n670Al_gkzo9pyIdv5ujA"
uri = "file://artifacts/mobile/assets/images/ospe/p011_internal_squint.png"
type = "image"
title = "generated_image"

[[generated]]
id = "GdM06RRkgT9QJmdX4Ai5D"
uri = "file://artifacts/mobile/assets/images/ospe/p012_foot_drop.png"
type = "image"
title = "generated_image"

[[generated]]
id = "0YDhUF6QiQoxsyK2Nh5ca"
uri = "file://artifacts/mobile/assets/images/ospe/p013_amniocentesis.png"
type = "image"
title = "generated_image"

[[generated]]
id = "gSZGJR0Oailx4mCaPdrzF"
uri = "file://artifacts/mobile/assets/images/ospe/p014_external_squint.png"
type = "image"
title = "generated_image"

[[generated]]
id = "-kwSl-iykWkGxB8xpKGKR"
uri = "file://artifacts/mobile/assets/images/ospe/p015_gluteal_injection.png"
type = "image"
title = "generated_image"

[[generated]]
id = "C04go3UNCNyEKptieQMpS"
uri = "file://artifacts/mobile/assets/images/ospe/p016_cdh.png"
type = "image"
title = "generated_image"

[[generated]]
id = "1urKZ1JIvUXHCs9Ku7Tx_"
uri = "file://artifacts/mobile/assets/images/ospe/p017_urethra.png"
type = "image"
title = "generated_image"

[[generated]]
id = "kByBvCKwHU1pXNDHwQd-3"
uri = "file://artifacts/mobile/assets/images/ospe/p018_wrist_drop.png"
type = "image"
title = "generated_image"

[[generated]]
id = "hAcOfBw7isflfItSvKnL7"
uri = "file://artifacts/mobile/assets/images/ospe/p019_waldeyers_ring.png"
type = "image"
title = "generated_image"

[[outputs]]
id = "94NV8f3RBIIbXEYx6N3Bm"
uri = "file://artifacts/mobile/assets/images/trophy.png"
type = "image"
title = "Cropped Golden Cup"

[[outputs]]
id = "WPDmPrwHsNkG_5Wa4p6cl"
uri = "file://medspotter-vercel.zip"
type = "unspecified"
title = "MedSpotter Deploy Package (zip)"
