uploads = []

[[generated]]
id = "JoacGhzjmjtPCymUXhmR_"
uri = "file://artifacts/mobile/assets/images/icon.png"
type = "image"
title = "histospotter app icon"

[[generated]]
id = "0vzijO0hLElEsbLib0S8U"
uri = "file://artifacts/mobile/assets/images/histo_epithelial.png"
type = "image"
title = "epithelial histology slide"

[[generated]]
id = "NUXmOm7TUYgWafA7Bn_xj"
uri = "file://artifacts/mobile/assets/images/histo_muscle.png"
type = "image"
title = "muscle histology slide"

[[generated]]
id = "_CNh5148E5fFTUPVhtzo6"
uri = "file://artifacts/mobile/assets/images/histo_kidney.png"
type = "image"
title = "kidney histology slide"

[[generated]]
id = "Y39nS1TTevHiWM6awC3pO"
uri = "file://artifacts/mobile/assets/images/histo_nerve.png"
type = "image"
title = "nerve histology slide"

[[generated]]
id = "c3uX8B5iPexmyxIYLenn4"
uri = "file://artifacts/mobile/assets/images/histo_liver.png"
type = "image"
title = "liver histology slide"

[[generated]]
id = "mb3aJmgv75jktT5C2EEPl"
uri = "file://artifacts/mobile/assets/images/histo_lung.png"
type = "image"
title = "lung histology slide"

[[generated]]
id = "e4xqxLs_hNYLqhwoNhJLM"
uri = "file://artifacts/mobile/assets/images/histo_skin.png"
type = "image"
title = "skin histology slide"

[[generated]]
id = "-amUj53asbnZyDk-ESsdx"
uri = "file://artifacts/mobile/assets/images/thumbnails/histology.png"
type = "image"
title = "histology slide thumbnail"

[[generated]]
id = "_xolnFtOfBgb-Z_FE5Klg"
uri = "file://artifacts/mobile/assets/images/thumbnails/head_neck.png"
type = "image"
title = "head neck anatomy thumbnail"

[[generated]]
id = "N8w1DdXt-rgDY-xKJN2VO"
uri = "file://artifacts/mobile/assets/images/thumbnails/upper_limb.png"
type = "image"
title = "upper limb anatomy thumbnail"

[[generated]]
id = "29Q6gr97zorB4PgFUO5JS"
uri = "file://artifacts/mobile/assets/images/thumbnails/thorax.png"
type = "image"
title = "thorax heart anatomy thumbnail"

[[generated]]
id = "ROGycwUfJmv_fITNJ4rWc"
uri = "file://artifacts/mobile/assets/images/thumbnails/abdomen.png"
type = "image"
title = "abdomen anatomy thumbnail"

[[generated]]
id = "Plpk2XUEmVV51Vg89hh8-"
uri = "file://artifacts/mobile/assets/images/thumbnails/neuroanatomy.png"
type = "image"
title = "brain neuroanatomy thumbnail"

[[generated]]
id = "RbpO3-oHj-NS9V5yen-md"
uri = "file://artifacts/mobile/assets/images/thumbnails/embryology.png"
type = "image"
title = "embryology stages thumbnail"

[[generated]]
id = "Jx-izxnayYWam4kohUVJT"
uri = "file://artifacts/mobile/assets/images/thumbnails/osteology.png"
type = "image"
title = "osteology bones thumbnail"

[[outputs]]
id = "94NV8f3RBIIbXEYx6N3Bm"
uri = "file://artifacts/mobile/assets/images/trophy.png"
type = "image"
title = "Cropped Golden Cup"

[[outputs]]
id = "WPDmPrwHsNkG_5Wa4p6cl"
uri = "file://medspotter-vercel.zip"
type = "unspecified"
title = "MedSpotter Deploy Package (zip)"
